### ISSUE TITLE
Incorrect result for wigner3j_f(48, 48, -48, 48)

### ISSUE THREAD

**Issue by hsgg** [xzackli/WignerFamilies.jl#11]
Comparison with WignerSymbols package gives:

```julia
julia> using WignerFamilies, WignerSymbols

julia> wigner3j_f(48, 48, -48, 48)  # WignerFamilies
0-element OffsetArray(::Array{Float64,1}, 1:0) with eltype Float64 with indices 1:0

julia> wigner3j.(Float64, 48, 48, 0:96, -48, 48)  # WignerSymbols
97-element Array{Float64,1}:
  0.1015346165133619
 -0.10049320830180843
  0.09844211070805879
 -0.09544316744020098
  0.09158527020791281
 -0.08698001112229858
  0.0817563591226414
...
```
Thanks for making the package available!

**Comment by xzackli** [comment]
Thank you, this is super helpful stuff. I'll take a look, and then add a regression test.

**Comment by xzackli** [comment]
@hsgg, it's a selection rule problem, thank you for finding this! I only use this package for science in a very limited range of `m` quantum numbers, so I've managed to never encounter this.

The example is kind of interesting -- the three term recursion relation is used in the lower half, and the two-term recursion on the upper half. The family moves exponentially towards zero as j increases, and the relative error follows it! That's exactly what should be happening in this algorithm, but it's still gratifying to see. 

I do notice that the transition region sees the largest error, which is what you expect from the dividing strategy of Luscombe and Luban. There's a recent paper ([Xu 2020](https://arxiv.org/abs/2006.04267)) which tries to avoid this by instead splitting the recursion into exponential and oscillatory components, which seems like it would apply well to this family.

![test](https://user-images.githubusercontent.com/8048811/104341393-bc576000-54c7-11eb-8382-f00328f42dce.png)

**Comment by hsgg** [comment]
Wow, thanks for fixing this so quickly!
